name: CI
on:
    pull_request:
        types: [closed]
        branches:
        - master
        - release/test
jobs:
  publish:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        version: [18]
    permissions:
      packages: read
      id-token: write
      contents: write
    concurrency:
      # pushes to same branch, to cancel out old actions
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.version }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update git branches locally
      run: git pull --no-tags --all
    - name: Checkout to GITHUB_HEAD_REF (lerna --since requires this)
      run: git checkout $GITHUB_HEAD_REF
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - name: Setup credentials for @blueflag and @92green npm
      run: ./scripts/setup-npm.sh
      shell: bash
      env:
        BLUEFLAG_GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.BLUEFLAG_GITHUB_PACKAGES_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Yarn Version
      run: yarn policies set-version 1.22.19
    - name: Yarn Install
      run: yarn install
      env:
        NPM_CONFIG_USERCONFIG: $GITHUB_WORKSPACE/.npmrc
        NODE_ENV: "development"
    - name: Yarn Install
      run: yarn lerna bootstrap
      env:
        NPM_CONFIG_USERCONFIG: $GITHUB_WORKSPACE/.npmrc
        NODE_ENV: "development"
    - name: "Version and publish"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = master ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        fi

        npx lerna publish from-git --yes